# Generated by Django 5.0.6 on 2024-05-15 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('bookID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('bookID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('authors', models.ManyToManyField(related_name='books', to='LMSystem.authors')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='LMSystem.category')),
            ],
        ),
        migrations.CreateModel(
            name='bookfile',
            fields=[
                ('fileID', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('mobi', 'MOBI'), ('epub', 'EPUB'), ('txt', 'TXT')], max_length=100)),
                ('filepath', models.FileField(default=None, max_length=255, null=True, upload_to='books/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='LMSystem.book')),
            ],
        ),
    ]
